FROM node:16-alpine AS builder

USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./

RUN npm run build

#BUILD IMAGE
FROM nginx
EXPOSE 3000

#OVERWRITING DEFAULT.CONF FILE
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

#COPYING PRODUCTION ASSETS FROM BUILDER IMAGE
COPY --from=builder /app/build /usr/share/nginx/html
