name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t makcsdev/multi-container -f ./client/dockerfile.dev ./client
      - run: docker run -e CI=true makcsdev/multi-container npm test

      - run: docker build -t makcsdev/multi-client ./client
      - run: docker build -t makcsdev/multi-nginx ./nginx
      - run: docker build -t makcsdev/multi-server ./server
      - run: docker build -t makcsdev/multi-worker ./worker

      - run: docker push makcsdev/multi-client
      - run: docker push makcsdev/multi-nginx
      - run: docker push makcsdev/multi-server
      - run: docker push makcsdev/multi-worker

        #=============AWS config===============
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-containers
          environment_name: Multi-containers-env
          existing_bucket_name: elasticbeanstalk-us-east-2-734800506751
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
